'-------------------------------------------------------------------------------
'  Copyright 2017 Pax, Schweizerische Lebensversicherungs-Gesellschaft AG
'
'  Licensed under the Pax License, Version 1.0 (the "License");
'-------------------------------------------------------------------------------
'
' Vorlage Class Diagramm
'-------------------------------------------------------------------------------

@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

center footer Copyright 2017 Pax, Schweizerische Lebensversicherungs-Gesellschaft AG

@enduml