<!---
Copyright 2017 Pax, Schweizerische Lebensversicherungs-Gesellschaft AG

Licensed under the Pax License, Version 1.0 (the "License");

Produce HTML pages with NodeJS/Aglio (install npm install aglio)

aglio -i your-source-file.apib -o /destination/api-v1.html
-->

FORMAT: 1A
HOST: http://lehrlingapp.dod.pax.ch/v1

# xyz API

xyz API documentation. General documentation. Links to more documentation.

# Data Structures

## xyzVertrag (object)
+ id: 25 (required, number) - A unique ID for xyzVertrag.
+ name: `BV-VertragXYZ` (string) - name of xyzVertrag.
+ eventdate: `2017-03-26T00:00` (string) - An ISO8601 date. date of event.

## xyzVertragList (array)
+ (xyzVertrag)

# Group xyzVertrag read 1 or list

Vertrags API's ....

## list of [/pax/bv/vertrag/{kriterien}]
Get list of xyz.

+ Parameters
    + kriterien: aktiv (required, string) - aktiv, to see aktiv Verträge; passiv, to see passiv Verträge

### Vertrag [GET]

Returns an array (list) of xyZVertrag.

+ Response 200 (application/json)

    + Attributes (xyzVertragList)

### Vertrag [POST]

Returns a result code.

+ Response 200 (application/json)


# Group service meta data

Information around service ....

## Version [/versions]

Version of the API

### Version [GET]

+ Response 200 (application/json)

        {
                "version": "4.1.1",
                "url": "http://xyz.pax.ch/api-v1.html"
        }
